create database BooksDB;
use BooksDB;
create table Books(title varchar(30),genre varchar(20),publication_year int,price int);
drop table Books;
create table Books(title varchar(30),author varchar(30),genre varchar(20),publication_year int,price int);
insert into Books values("To Kill a Mockingbird","Harper Lee","Fiction",1960,300);
insert into Books values( "The Alchemist","Paulo Coelho","Inspirational",1988,200);
insert into Books values(" The Da Vinci Code","Dan Brown","Thriller",2003,400);
insert into Books values("The marvel avengers","joss whedon","action",2018,100);
insert into Books values("Civil war","stan lee","strugguling",2019,500);
insert into Books values("infinity war","jack kirby","team work",2020,800);
insert into Books values("End game","zak penn","exellence",2021,900);
insert into Books values("shan chi","Prasad","Historical",2022,1100);
insert into Books values("The legend of 10 rings","Durga","fantasy",2023,1000);
insert into Books values("The secret wars","Jagadeesh","memoir",2024,1500);
select * from Books;
select title from books;
select * from Books where title="infinity war";
update Books set price=1900 where title="The legend of 10 rings";
select * from Books;
delete from Books where title="Civil war";
select * from Books;